// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: git/provider.proto

package git

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRepositoryNamesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetRepositoryNamesRequest) Reset() {
	*x = GetRepositoryNamesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_git_provider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRepositoryNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryNamesRequest) ProtoMessage() {}

func (x *GetRepositoryNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_git_provider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryNamesRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryNamesRequest) Descriptor() ([]byte, []int) {
	return file_git_provider_proto_rawDescGZIP(), []int{0}
}

// message GetRepositoryNamesResponse {
//   string name = 1;
// }
type GetRepositoryNamesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *GetRepositoryNamesResponse) Reset() {
	*x = GetRepositoryNamesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_git_provider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRepositoryNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryNamesResponse) ProtoMessage() {}

func (x *GetRepositoryNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_git_provider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryNamesResponse.ProtoReflect.Descriptor instead.
func (*GetRepositoryNamesResponse) Descriptor() ([]byte, []int) {
	return file_git_provider_proto_rawDescGZIP(), []int{1}
}

func (x *GetRepositoryNamesResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

var File_git_provider_proto protoreflect.FileDescriptor

var file_git_provider_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x69, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x67, 0x69, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x32, 0x64, 0x0a, 0x0b, 0x47, 0x69,
	0x74, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x55, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12,
	0x1e, 0x2e, 0x67, 0x69, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x67, 0x69, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x67, 0x69, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_git_provider_proto_rawDescOnce sync.Once
	file_git_provider_proto_rawDescData = file_git_provider_proto_rawDesc
)

func file_git_provider_proto_rawDescGZIP() []byte {
	file_git_provider_proto_rawDescOnce.Do(func() {
		file_git_provider_proto_rawDescData = protoimpl.X.CompressGZIP(file_git_provider_proto_rawDescData)
	})
	return file_git_provider_proto_rawDescData
}

var file_git_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_git_provider_proto_goTypes = []interface{}{
	(*GetRepositoryNamesRequest)(nil),  // 0: git.GetRepositoryNamesRequest
	(*GetRepositoryNamesResponse)(nil), // 1: git.GetRepositoryNamesResponse
}
var file_git_provider_proto_depIdxs = []int32{
	0, // 0: git.GitProvider.GetRepositoryNames:input_type -> git.GetRepositoryNamesRequest
	1, // 1: git.GitProvider.GetRepositoryNames:output_type -> git.GetRepositoryNamesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_git_provider_proto_init() }
func file_git_provider_proto_init() {
	if File_git_provider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_git_provider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRepositoryNamesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_git_provider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRepositoryNamesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_git_provider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_git_provider_proto_goTypes,
		DependencyIndexes: file_git_provider_proto_depIdxs,
		MessageInfos:      file_git_provider_proto_msgTypes,
	}.Build()
	File_git_provider_proto = out.File
	file_git_provider_proto_rawDesc = nil
	file_git_provider_proto_goTypes = nil
	file_git_provider_proto_depIdxs = nil
}
